CXX = g++
CXXFLAGS = -Wall -std=c++11 -g
Lab3: Database.o Graph.o Node.o Parameter.o Parser.o Predicate.o Query.o Relation.o Rule.o Scanner.o Scheme.o Token.o Tuple.o main.o
	$(CXX) $(CXXFLAGS) -o Lab3 Database.o Graph.o Node.o Parameter.o Parser.o Predicate.o Query.o Relation.o Rule.o Scanner.o Scheme.o Token.o Tuple.o main.o
Database.o: Database.h
Graph.o: Graph.h
Node.o: Node.h
Parameter.o: Parameter.h
Parser.o: Parser.h
Predicate.o: Predicate.h
Query.o: Query.h
Relation.o: Relation.h
Rule.o: Rule.h
Scanner.o: Scanner.h
Scheme.o: Scheme.h
Token.o: Token.h
Tuple.o: Tuple.h
main.o: main.cpp